[manager]
ratio          = [1, 3, 4]
tab_width      = 1
sort_by        = "alphabetical"
sort_sensitive = false
sort_reverse   = false
show_hidden    = false
show_symlink   = true

[opener]
edit = [
  { run = 'nvim "$@"', block = true, desc = "nvim" },
]
open = [
  { run = 'xdg-open "$@"', desc = "Open" },
]

[open]
rules = [
  { mime = "text/*",        use = "edit" },
  { mime = "application/json", use = "edit" },
  { mime = "application/toml", use = "edit" },
  { mime = "inode/x-empty", use = "edit" },
  { mime = "*",             use = "open" },
]
