# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "vmd" "nvme" "usb_storage" "usbhid" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-28cb35f0-a3bf-40a4-894c-bc2bb27a71b7";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-28cb35f0-a3bf-40a4-894c-bc2bb27a71b7".device = "/dev/disk/by-uuid/28cb35f0-a3bf-40a4-894c-bc2bb27a71b7";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0215-0CA2";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/home/user/Volumes/shared-part" = {
    device  = "/dev/disk/by-uuid/70725C43725C1068";
    fsType  = "ntfs-3g";
    options = [
      "uid=1000" "gid=1000"
      "dmask=007" "fmask=117"
      "nofail"
      "x-systemd.automount"
      "x-systemd.device-timeout=5"
      "x-systemd.mount-timeout=5"
    ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
